const APPLICATION_SERVICE_CODES = {
    MATCH_EXISTS_ERROR: "MATCH_EXISTS_ERROR",
    USER_EXISTS_ERROR: "USER_EXISTS_ERROR",
    IS_TEAM_MEMBER_ERROR: "IS_TEAM_MEMBER_ERROR",
    TEAM_EXISTS_ERROR: "TEAM_EXISTS_ERROR",
    PLAYER_EXISTS_ERROR: "PLAYER_EXISTS_ERROR",
    IS_VALID_GOAL_ERROR: "IS_VALID_GOAL_ERROR",
    CAN_ADD_GOAL_ERROR: "CAN_ADD_GOAL_ERROR",
    IS_VALID_MATCH_DATES_ERROR: "IS_VALID_MATCH_DATES_ERROR",
    CAN_ADD_TEAM_MEMBERSHIP_ERROR: "CAN_ADD_TEAM_MEMBERSHIP_ERROR",
    TEAM_MEMBERSHIP_EXISTS_ERROR: "TEAM_MEMBERSHIP_EXISTS_ERROR",
};

export default APPLICATION_SERVICE_CODES;
