const APPLICATION_VALIDATOR_CODES = {
    IS_MATCH_TEAM_ERROR: "IS_MATCH_TEAM_ERROR",
    MATCH_EXISTS_ERROR: "MATCH_EXISTS_ERROR",
    IS_TEAM_MEMBER_ERROR: "IS_TEAM_MEMBER_ERROR",
    TEAM_EXISTS_ERROR: "TEAM_EXISTS_ERROR",
    PLAYER_EXISTS_ERROR: "PLAYER_EXISTS_ERROR",
    IS_VALID_GOAL_ERROR: "IS_VALID_GOAL_ERROR",
    CAN_ADD_GOAL_ERROR: "CAN_ADD_GOAL_ERROR",
};

export default APPLICATION_VALIDATOR_CODES;
